#!/bin/bash
#PBS -N  Deconvolve
#MSUB -l nodes=1:ppn=1
#MSUB -l walltime=1:00:00:00
#MSUB -l pmem=8000mb
#MSUB -q singlenode
#MSUB -j oe
#

#export FERMI_DIR=/home/tu/tu_tu/tu_pside01/fermi_source/ScienceTools-v11r5p3-fssc-20180124-x86_64-unknown-linux-gnu-libc2.17/x86_64-unknown-linux-gnu-libc2.17/ ;
#source $FERMI_DIR/fermi-init.sh

#
#export pf=/home/tu/tu_tu/tu_pside01/Pfiles/pfiles_deconv
#mkdir ${pf}

#export PFILES="${pf};/home/tu/tu_tu/tu_pside01/fermi_source/ScienceTools-v11r5p3-fssc-20180124-x86_64-unknown-linux-gnu-libc2.17/x86_64-unknown-linux-gnu-libc2.17/syspfiles"

#
#cd /home/tu/tu_tu/tu_pside01/FERMI/Work/Deconvolution

python make_fermi_maps.py 
